language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.0.*

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
  - php composer.phar update

script: ./vendor/bin/phpunit --coverage-text
