<?php

namespace DotSmart\SmsBundle\Repository;

/**
 * DotSmartSmsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DotSmartSmsRepository extends \Doctrine\ORM\EntityRepository
{
}
